// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestProject.Data.Context;

namespace TestProject.Data.Migrations
{
    [DbContext(typeof(TestProjectDbContext))]
    [Migration("20200223015719_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestProject.Domain.Entities.CityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tbilisi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kutaisi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rustavi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Telavi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Zugdidi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Khashuri"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Zestafoni"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Marneuli"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Batumi"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tsiatura"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Borjomi"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Kaspi"
                        });
                });

            modelBuilder.Entity("TestProject.Domain.Entities.PersonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(100);

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasColumnType("char(11)")
                        .IsFixedLength(true);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName");

                    b.HasIndex("PersonalNumber")
                        .IsUnique();

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            DateOfBirth = new DateTime(2052, 1, 25, 5, 57, 17, 952, DateTimeKind.Local).AddTicks(7788),
                            FirstName = "Irakli",
                            Gender = (byte)0,
                            LastName = "Zarandia",
                            PersonalNumber = "00000465813"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 5,
                            DateOfBirth = new DateTime(2048, 9, 23, 5, 57, 17, 954, DateTimeKind.Local).AddTicks(5953),
                            FirstName = "Zviadi",
                            Gender = (byte)0,
                            LastName = "Gamsaxurdia",
                            PersonalNumber = "00000314137"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            DateOfBirth = new DateTime(2041, 11, 1, 5, 57, 17, 954, DateTimeKind.Local).AddTicks(6074),
                            FirstName = "Eduardi",
                            Gender = (byte)0,
                            LastName = "Shevardnaze",
                            PersonalNumber = "00000895687"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            DateOfBirth = new DateTime(2045, 12, 1, 5, 57, 17, 954, DateTimeKind.Local).AddTicks(6102),
                            FirstName = "Mikheili",
                            Gender = (byte)0,
                            LastName = "Saakashvili",
                            PersonalNumber = "00000171103"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            DateOfBirth = new DateTime(2112, 3, 19, 5, 57, 17, 954, DateTimeKind.Local).AddTicks(6124),
                            FirstName = "Giorgi",
                            Gender = (byte)0,
                            LastName = "Margvelashvili",
                            PersonalNumber = "00000817832"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 5,
                            DateOfBirth = new DateTime(2115, 4, 21, 5, 57, 17, 954, DateTimeKind.Local).AddTicks(6154),
                            FirstName = "Salome",
                            Gender = (byte)1,
                            LastName = "Zurabishvili",
                            PersonalNumber = "00000623628"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 6,
                            DateOfBirth = new DateTime(2044, 9, 4, 5, 57, 17, 954, DateTimeKind.Local).AddTicks(6176),
                            FirstName = "Leqo",
                            Gender = (byte)0,
                            LastName = "Nidzaradze",
                            PersonalNumber = "00000182603"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 6,
                            DateOfBirth = new DateTime(2090, 5, 17, 5, 57, 17, 954, DateTimeKind.Local).AddTicks(6199),
                            FirstName = "Bidzina",
                            Gender = (byte)0,
                            LastName = "Tabagari",
                            PersonalNumber = "00000716033"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 8,
                            DateOfBirth = new DateTime(2117, 6, 29, 5, 57, 17, 954, DateTimeKind.Local).AddTicks(6218),
                            FirstName = "Geno",
                            Gender = (byte)0,
                            LastName = "Shavdia",
                            PersonalNumber = "00000149762"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 8,
                            DateOfBirth = new DateTime(2098, 8, 14, 5, 57, 17, 954, DateTimeKind.Local).AddTicks(6246),
                            FirstName = "Rezo",
                            Gender = (byte)0,
                            LastName = "Khatamadze",
                            PersonalNumber = "00000081132"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 11,
                            DateOfBirth = new DateTime(2091, 6, 14, 5, 57, 17, 954, DateTimeKind.Local).AddTicks(6267),
                            FirstName = "გურამი",
                            Gender = (byte)0,
                            LastName = "ჯონირია",
                            PersonalNumber = "00000219816"
                        },
                        new
                        {
                            Id = 12,
                            CityId = 11,
                            DateOfBirth = new DateTime(2088, 8, 1, 5, 57, 17, 954, DateTimeKind.Local).AddTicks(6285),
                            FirstName = "ომგერი",
                            Gender = (byte)0,
                            LastName = "კაკაურიძე",
                            PersonalNumber = "00000002205"
                        },
                        new
                        {
                            Id = 13,
                            CityId = 11,
                            DateOfBirth = new DateTime(2085, 10, 5, 5, 57, 17, 954, DateTimeKind.Local).AddTicks(6308),
                            FirstName = "უჩა",
                            Gender = (byte)0,
                            LastName = "ზერაგია",
                            PersonalNumber = "00000840617"
                        },
                        new
                        {
                            Id = 14,
                            CityId = 11,
                            DateOfBirth = new DateTime(2105, 11, 16, 5, 57, 17, 954, DateTimeKind.Local).AddTicks(6334),
                            FirstName = "Dinara",
                            Gender = (byte)1,
                            LastName = "Chkadua",
                            PersonalNumber = "00000622022"
                        },
                        new
                        {
                            Id = 15,
                            CityId = 2,
                            DateOfBirth = new DateTime(2075, 5, 9, 5, 57, 17, 954, DateTimeKind.Local).AddTicks(6363),
                            FirstName = "Lela",
                            Gender = (byte)1,
                            LastName = "Tsurtsumia",
                            PersonalNumber = "00000563934"
                        },
                        new
                        {
                            Id = 16,
                            CityId = 2,
                            DateOfBirth = new DateTime(2120, 6, 17, 5, 57, 17, 954, DateTimeKind.Local).AddTicks(6392),
                            FirstName = "Inga",
                            Gender = (byte)1,
                            LastName = "Grigolia",
                            PersonalNumber = "00000988157"
                        });
                });

            modelBuilder.Entity("TestProject.Domain.Entities.PhoneNumberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PhoneNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = "00000790065",
                            PersonId = 1,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 2,
                            Number = "00000646016",
                            PersonId = 1,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            Number = "00000271315",
                            PersonId = 1,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 4,
                            Number = "00000222640",
                            PersonId = 2,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 5,
                            Number = "00000395255",
                            PersonId = 2,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 6,
                            Number = "00000808365",
                            PersonId = 2,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 7,
                            Number = "00000376430",
                            PersonId = 3,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 8,
                            Number = "00000122198",
                            PersonId = 3,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 9,
                            Number = "00000067900",
                            PersonId = 3,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 10,
                            Number = "00000468570",
                            PersonId = 4,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 11,
                            Number = "00000128391",
                            PersonId = 5,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 12,
                            Number = "00000045490",
                            PersonId = 6,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 13,
                            Number = "00000095316",
                            PersonId = 6,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 14,
                            Number = "00000840651",
                            PersonId = 6,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 15,
                            Number = "00000484980",
                            PersonId = 7,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 16,
                            Number = "00000564913",
                            PersonId = 8,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 17,
                            Number = "00000669484",
                            PersonId = 9,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 18,
                            Number = "00000051109",
                            PersonId = 9,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 19,
                            Number = "00000467375",
                            PersonId = 9,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 20,
                            Number = "00000137156",
                            PersonId = 10,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 21,
                            Number = "00000219157",
                            PersonId = 10,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 22,
                            Number = "00000151000",
                            PersonId = 11,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 23,
                            Number = "00000405463",
                            PersonId = 11,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 24,
                            Number = "00000374999",
                            PersonId = 11,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 25,
                            Number = "00000729289",
                            PersonId = 12,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 26,
                            Number = "00000092534",
                            PersonId = 12,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 27,
                            Number = "00000696239",
                            PersonId = 13,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 28,
                            Number = "00000649200",
                            PersonId = 13,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 29,
                            Number = "00000553098",
                            PersonId = 14,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 30,
                            Number = "00000546161",
                            PersonId = 14,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 31,
                            Number = "00000402407",
                            PersonId = 14,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 32,
                            Number = "00000232670",
                            PersonId = 15,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 33,
                            Number = "00000747313",
                            PersonId = 15,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 34,
                            Number = "00000546818",
                            PersonId = 16,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 35,
                            Number = "00000948634",
                            PersonId = 16,
                            Type = (byte)1
                        });
                });

            modelBuilder.Entity("TestProject.Domain.Entities.RelatedPersonEntity", b =>
                {
                    b.Property<int>("RelatedPersonId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<byte>("RelationType")
                        .HasColumnType("tinyint");

                    b.HasKey("RelatedPersonId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("RelatedPersons");
                });

            modelBuilder.Entity("TestProject.Domain.Entities.PersonEntity", b =>
                {
                    b.HasOne("TestProject.Domain.Entities.CityEntity", "City")
                        .WithMany("Persons")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TestProject.Domain.Entities.PhoneNumberEntity", b =>
                {
                    b.HasOne("TestProject.Domain.Entities.PersonEntity", "Person")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestProject.Domain.Entities.RelatedPersonEntity", b =>
                {
                    b.HasOne("TestProject.Domain.Entities.PersonEntity", "Person")
                        .WithMany("RelatedPersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TestProject.Domain.Entities.PersonEntity", "RelatedPerson")
                        .WithMany()
                        .HasForeignKey("RelatedPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
