// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestProject.Data.Context;

namespace TestProject.Data.Migrations
{
    [DbContext(typeof(TestProjectDbContext))]
    partial class TestProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TestProject.Domain.Entities.CityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tbilisi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kutaisi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rustavi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Telavi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Zugdidi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Khashuri"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Zestafoni"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Marneuli"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Batumi"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tsiatura"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Borjomi"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Kaspi"
                        });
                });

            modelBuilder.Entity("TestProject.Domain.Entities.PersonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(100);

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasColumnType("char(11)")
                        .IsFixedLength(true);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName");

                    b.HasIndex("PersonalNumber")
                        .IsUnique();

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            DateOfBirth = new DateTime(2043, 2, 11, 5, 30, 56, 778, DateTimeKind.Local).AddTicks(4149),
                            FirstName = "Irakli",
                            Gender = (byte)0,
                            LastName = "Zarandia",
                            PersonalNumber = "00000248035"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 5,
                            DateOfBirth = new DateTime(2069, 3, 5, 5, 30, 56, 779, DateTimeKind.Local).AddTicks(6619),
                            FirstName = "Zviadi",
                            Gender = (byte)0,
                            LastName = "Gamsaxurdia",
                            PersonalNumber = "00000871494"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            DateOfBirth = new DateTime(2079, 9, 16, 5, 30, 56, 779, DateTimeKind.Local).AddTicks(6676),
                            FirstName = "Eduardi",
                            Gender = (byte)0,
                            LastName = "Shevardnaze",
                            PersonalNumber = "00000875538"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            DateOfBirth = new DateTime(2058, 11, 30, 5, 30, 56, 779, DateTimeKind.Local).AddTicks(6690),
                            FirstName = "Mikheili",
                            Gender = (byte)0,
                            LastName = "Saakashvili",
                            PersonalNumber = "00000540348"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            DateOfBirth = new DateTime(2092, 2, 5, 5, 30, 56, 779, DateTimeKind.Local).AddTicks(6700),
                            FirstName = "Giorgi",
                            Gender = (byte)0,
                            LastName = "Margvelashvili",
                            PersonalNumber = "00000762571"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 5,
                            DateOfBirth = new DateTime(2108, 2, 19, 5, 30, 56, 779, DateTimeKind.Local).AddTicks(6718),
                            FirstName = "Salome",
                            Gender = (byte)1,
                            LastName = "Zurabishvili",
                            PersonalNumber = "00000772159"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 6,
                            DateOfBirth = new DateTime(2071, 4, 18, 5, 30, 56, 779, DateTimeKind.Local).AddTicks(6729),
                            FirstName = "Leqo",
                            Gender = (byte)0,
                            LastName = "Nidzaradze",
                            PersonalNumber = "00000895172"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 6,
                            DateOfBirth = new DateTime(2096, 11, 4, 5, 30, 56, 779, DateTimeKind.Local).AddTicks(6740),
                            FirstName = "Bidzina",
                            Gender = (byte)0,
                            LastName = "Tabagari",
                            PersonalNumber = "00000195494"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 8,
                            DateOfBirth = new DateTime(2104, 9, 28, 5, 30, 56, 779, DateTimeKind.Local).AddTicks(6752),
                            FirstName = "Geno",
                            Gender = (byte)0,
                            LastName = "Shavdia",
                            PersonalNumber = "00000317370"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 8,
                            DateOfBirth = new DateTime(2105, 6, 24, 5, 30, 56, 779, DateTimeKind.Local).AddTicks(6765),
                            FirstName = "Rezo",
                            Gender = (byte)0,
                            LastName = "Khatamadze",
                            PersonalNumber = "00000518124"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 11,
                            DateOfBirth = new DateTime(2076, 1, 23, 5, 30, 56, 779, DateTimeKind.Local).AddTicks(6776),
                            FirstName = "გურამი",
                            Gender = (byte)0,
                            LastName = "ჯონირია",
                            PersonalNumber = "00000749864"
                        },
                        new
                        {
                            Id = 12,
                            CityId = 11,
                            DateOfBirth = new DateTime(2092, 5, 30, 5, 30, 56, 779, DateTimeKind.Local).AddTicks(6787),
                            FirstName = "ომგერი",
                            Gender = (byte)0,
                            LastName = "კაკაურიძე",
                            PersonalNumber = "00000343590"
                        },
                        new
                        {
                            Id = 13,
                            CityId = 11,
                            DateOfBirth = new DateTime(2057, 4, 22, 5, 30, 56, 779, DateTimeKind.Local).AddTicks(6798),
                            FirstName = "უჩა",
                            Gender = (byte)0,
                            LastName = "ზერაგია",
                            PersonalNumber = "00000065554"
                        },
                        new
                        {
                            Id = 14,
                            CityId = 11,
                            DateOfBirth = new DateTime(2111, 12, 5, 5, 30, 56, 779, DateTimeKind.Local).AddTicks(6808),
                            FirstName = "Dinara",
                            Gender = (byte)1,
                            LastName = "Chkadua",
                            PersonalNumber = "00000743199"
                        },
                        new
                        {
                            Id = 15,
                            CityId = 2,
                            DateOfBirth = new DateTime(2043, 2, 16, 5, 30, 56, 779, DateTimeKind.Local).AddTicks(6820),
                            FirstName = "Lela",
                            Gender = (byte)1,
                            LastName = "Tsurtsumia",
                            PersonalNumber = "00000189132"
                        },
                        new
                        {
                            Id = 16,
                            CityId = 2,
                            DateOfBirth = new DateTime(2086, 12, 26, 5, 30, 56, 779, DateTimeKind.Local).AddTicks(6831),
                            FirstName = "Inga",
                            Gender = (byte)1,
                            LastName = "Grigolia",
                            PersonalNumber = "00000062392"
                        });
                });

            modelBuilder.Entity("TestProject.Domain.Entities.PhoneNumberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PhoneNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = "00000049181",
                            PersonId = 1,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 2,
                            Number = "00000964223",
                            PersonId = 1,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            Number = "00000220552",
                            PersonId = 1,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 4,
                            Number = "00000807909",
                            PersonId = 2,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 5,
                            Number = "00000297758",
                            PersonId = 2,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 6,
                            Number = "00000204954",
                            PersonId = 3,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 7,
                            Number = "00000551795",
                            PersonId = 3,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 8,
                            Number = "00000010414",
                            PersonId = 3,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 9,
                            Number = "00000971401",
                            PersonId = 4,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 10,
                            Number = "00000362102",
                            PersonId = 4,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 11,
                            Number = "00000080642",
                            PersonId = 4,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 12,
                            Number = "00000354085",
                            PersonId = 5,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 13,
                            Number = "00000209996",
                            PersonId = 5,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 14,
                            Number = "00000405129",
                            PersonId = 5,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 15,
                            Number = "00000110097",
                            PersonId = 6,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 16,
                            Number = "00000315792",
                            PersonId = 7,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 17,
                            Number = "00000033786",
                            PersonId = 7,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 18,
                            Number = "00000369124",
                            PersonId = 8,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 19,
                            Number = "00000074155",
                            PersonId = 9,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 20,
                            Number = "00000049256",
                            PersonId = 10,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 21,
                            Number = "00000787037",
                            PersonId = 10,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 22,
                            Number = "00000453490",
                            PersonId = 11,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 23,
                            Number = "00000814120",
                            PersonId = 11,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 24,
                            Number = "00000454572",
                            PersonId = 12,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 25,
                            Number = "00000012080",
                            PersonId = 12,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 26,
                            Number = "00000514463",
                            PersonId = 13,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 27,
                            Number = "00000578050",
                            PersonId = 14,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 28,
                            Number = "00000494701",
                            PersonId = 14,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 29,
                            Number = "00000538373",
                            PersonId = 15,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 30,
                            Number = "00000125923",
                            PersonId = 15,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 31,
                            Number = "00000685453",
                            PersonId = 15,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 32,
                            Number = "00000173153",
                            PersonId = 16,
                            Type = (byte)0
                        });
                });

            modelBuilder.Entity("TestProject.Domain.Entities.RelatedPersonEntity", b =>
                {
                    b.Property<int>("RelatedPersonId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<byte>("RelationType")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("RelatedPersonId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("RelatedPersons");
                });

            modelBuilder.Entity("TestProject.Domain.Entities.PersonEntity", b =>
                {
                    b.HasOne("TestProject.Domain.Entities.CityEntity", "City")
                        .WithMany("Persons")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TestProject.Domain.Entities.PhoneNumberEntity", b =>
                {
                    b.HasOne("TestProject.Domain.Entities.PersonEntity", "Person")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestProject.Domain.Entities.RelatedPersonEntity", b =>
                {
                    b.HasOne("TestProject.Domain.Entities.PersonEntity", "Person")
                        .WithMany("RelatedPersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProject.Domain.Entities.PersonEntity", "RelatedPerson")
                        .WithMany()
                        .HasForeignKey("RelatedPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
