// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestProject.Data.Context;

namespace TestProject.Data.Migrations
{
    [DbContext(typeof(TestProjectDbContext))]
    partial class TestProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestProject.Domain.Entities.CityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tbilisi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kutaisi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rustavi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Telavi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Zugdidi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Khashuri"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Zestafoni"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Marneuli"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Batumi"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tsiatura"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Borjomi"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Kaspi"
                        });
                });

            modelBuilder.Entity("TestProject.Domain.Entities.PersonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(100);

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasColumnType("char(11)")
                        .IsFixedLength(true);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName");

                    b.HasIndex("PersonalNumber")
                        .IsUnique();

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            DateOfBirth = new DateTime(1975, 11, 8, 6, 5, 40, 411, DateTimeKind.Local).AddTicks(1479),
                            FirstName = "Irakli",
                            Gender = (byte)0,
                            LastName = "Zarandia",
                            PersonalNumber = "00000356154"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 5,
                            DateOfBirth = new DateTime(2000, 1, 15, 6, 5, 40, 412, DateTimeKind.Local).AddTicks(2797),
                            FirstName = "Zviadi",
                            Gender = (byte)0,
                            LastName = "Gamsaxurdia",
                            PersonalNumber = "00000641250"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            DateOfBirth = new DateTime(1975, 6, 27, 6, 5, 40, 412, DateTimeKind.Local).AddTicks(2852),
                            FirstName = "Eduardi",
                            Gender = (byte)0,
                            LastName = "Shevardnaze",
                            PersonalNumber = "00000867034"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            DateOfBirth = new DateTime(1988, 8, 5, 6, 5, 40, 412, DateTimeKind.Local).AddTicks(2866),
                            FirstName = "Mikheili",
                            Gender = (byte)0,
                            LastName = "Saakashvili",
                            PersonalNumber = "00000485913"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            DateOfBirth = new DateTime(1985, 2, 4, 6, 5, 40, 412, DateTimeKind.Local).AddTicks(2884),
                            FirstName = "Giorgi",
                            Gender = (byte)0,
                            LastName = "Margvelashvili",
                            PersonalNumber = "00000164487"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 5,
                            DateOfBirth = new DateTime(1986, 10, 2, 6, 5, 40, 412, DateTimeKind.Local).AddTicks(2907),
                            FirstName = "Salome",
                            Gender = (byte)1,
                            LastName = "Zurabishvili",
                            PersonalNumber = "00000821019"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 6,
                            DateOfBirth = new DateTime(1995, 11, 25, 6, 5, 40, 412, DateTimeKind.Local).AddTicks(2918),
                            FirstName = "Leqo",
                            Gender = (byte)0,
                            LastName = "Nidzaradze",
                            PersonalNumber = "00000074083"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 6,
                            DateOfBirth = new DateTime(1981, 11, 3, 6, 5, 40, 412, DateTimeKind.Local).AddTicks(2929),
                            FirstName = "Bidzina",
                            Gender = (byte)0,
                            LastName = "Tabagari",
                            PersonalNumber = "00000391136"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 8,
                            DateOfBirth = new DateTime(1980, 5, 18, 6, 5, 40, 412, DateTimeKind.Local).AddTicks(2939),
                            FirstName = "Geno",
                            Gender = (byte)0,
                            LastName = "Shavdia",
                            PersonalNumber = "00000859549"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 8,
                            DateOfBirth = new DateTime(1956, 11, 2, 6, 5, 40, 412, DateTimeKind.Local).AddTicks(2952),
                            FirstName = "Rezo",
                            Gender = (byte)0,
                            LastName = "Khatamadze",
                            PersonalNumber = "00000148158"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 11,
                            DateOfBirth = new DateTime(2003, 1, 14, 6, 5, 40, 412, DateTimeKind.Local).AddTicks(2962),
                            FirstName = "გურამი",
                            Gender = (byte)0,
                            LastName = "ჯონირია",
                            PersonalNumber = "00000616809"
                        },
                        new
                        {
                            Id = 12,
                            CityId = 11,
                            DateOfBirth = new DateTime(1966, 12, 4, 6, 5, 40, 412, DateTimeKind.Local).AddTicks(2972),
                            FirstName = "ომგერი",
                            Gender = (byte)0,
                            LastName = "კაკაურიძე",
                            PersonalNumber = "00000782139"
                        },
                        new
                        {
                            Id = 13,
                            CityId = 11,
                            DateOfBirth = new DateTime(1963, 7, 26, 6, 5, 40, 412, DateTimeKind.Local).AddTicks(2983),
                            FirstName = "უჩა",
                            Gender = (byte)0,
                            LastName = "ზერაგია",
                            PersonalNumber = "00000897696"
                        },
                        new
                        {
                            Id = 14,
                            CityId = 11,
                            DateOfBirth = new DateTime(1948, 2, 13, 6, 5, 40, 412, DateTimeKind.Local).AddTicks(2993),
                            FirstName = "Dinara",
                            Gender = (byte)1,
                            LastName = "Chkadua",
                            PersonalNumber = "00000164447"
                        },
                        new
                        {
                            Id = 15,
                            CityId = 2,
                            DateOfBirth = new DateTime(1978, 9, 18, 6, 5, 40, 412, DateTimeKind.Local).AddTicks(3138),
                            FirstName = "Lela",
                            Gender = (byte)1,
                            LastName = "Tsurtsumia",
                            PersonalNumber = "00000361444"
                        },
                        new
                        {
                            Id = 16,
                            CityId = 2,
                            DateOfBirth = new DateTime(2006, 4, 19, 6, 5, 40, 412, DateTimeKind.Local).AddTicks(3149),
                            FirstName = "Inga",
                            Gender = (byte)1,
                            LastName = "Grigolia",
                            PersonalNumber = "00000219804"
                        });
                });

            modelBuilder.Entity("TestProject.Domain.Entities.PhoneNumberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PhoneNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = "00000726871",
                            PersonId = 1,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 2,
                            Number = "00000269300",
                            PersonId = 1,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            Number = "00000012838",
                            PersonId = 2,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 4,
                            Number = "00000188631",
                            PersonId = 3,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 5,
                            Number = "00000984454",
                            PersonId = 4,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 6,
                            Number = "00000150510",
                            PersonId = 4,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 7,
                            Number = "00000256751",
                            PersonId = 5,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 8,
                            Number = "00000542007",
                            PersonId = 6,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 9,
                            Number = "00000844708",
                            PersonId = 6,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 10,
                            Number = "00000729033",
                            PersonId = 7,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 11,
                            Number = "00000605234",
                            PersonId = 8,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 12,
                            Number = "00000774127",
                            PersonId = 9,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 13,
                            Number = "00000736031",
                            PersonId = 10,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 14,
                            Number = "00000539898",
                            PersonId = 11,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 15,
                            Number = "00000622724",
                            PersonId = 12,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 16,
                            Number = "00000613026",
                            PersonId = 13,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 17,
                            Number = "00000007018",
                            PersonId = 13,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 18,
                            Number = "00000698282",
                            PersonId = 13,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 19,
                            Number = "00000290906",
                            PersonId = 14,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 20,
                            Number = "00000866474",
                            PersonId = 15,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 21,
                            Number = "00000640103",
                            PersonId = 15,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 22,
                            Number = "00000179517",
                            PersonId = 15,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 23,
                            Number = "00000900573",
                            PersonId = 16,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = 24,
                            Number = "00000176968",
                            PersonId = 16,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 25,
                            Number = "00000110126",
                            PersonId = 16,
                            Type = (byte)2
                        });
                });

            modelBuilder.Entity("TestProject.Domain.Entities.RelatedPersonEntity", b =>
                {
                    b.Property<int>("RelatedPersonId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<byte>("RelationType")
                        .HasColumnType("tinyint");

                    b.HasKey("RelatedPersonId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("RelatedPersons");
                });

            modelBuilder.Entity("TestProject.Domain.Entities.PersonEntity", b =>
                {
                    b.HasOne("TestProject.Domain.Entities.CityEntity", "City")
                        .WithMany("Persons")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TestProject.Domain.Entities.PhoneNumberEntity", b =>
                {
                    b.HasOne("TestProject.Domain.Entities.PersonEntity", "Person")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestProject.Domain.Entities.RelatedPersonEntity", b =>
                {
                    b.HasOne("TestProject.Domain.Entities.PersonEntity", "Person")
                        .WithMany("RelatedPersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TestProject.Domain.Entities.PersonEntity", "RelatedPerson")
                        .WithMany()
                        .HasForeignKey("RelatedPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
